### PR TITLE
Update to current Meilisearch v1.0

### PR DESCRIPTION
**Pull request by Calamari**
There were multiple problems with using the current version of Meilisearch.

I fixed all those and also switched from Hackney/Httpoison to Finch via Req.

Hope you like that change. Also I would be glad if you could publish the new version. If you need a maintainer, or want to transfer the package, I like to help, since we are using Meilisearch and Elixir in our projects.

### CODE REVIEW

**Comment by robottokauf3** [comment]
@Calamari Awesome.  Thanks for the contribution.  I'll try to review, merge, and publish the updates this weekend.

**Comment by Calamari** [comment]
Cool.

I am also thinking about exposing the `wait_for_task` helper to the outside world. Maybe as `Meilisearch.Tasks.wait_until_finished` or something similar. Since it is a nice feature which I also kind of replicated in our environment, since it is nice to have, when trying to write a setup script for on environment.

**Comment by Calamari** [comment]
Damn. wrong button. :-D

Cool. Please be aware, that I also wrote down in the README that it is a good idea to keep the client version in sync with the Meilisearch version.

**Comment by robottokauf3** [comment]
The PR looks good to me.  I'm merging now, and will push a release tomorrow.

**Pull request merged**
