### PR TITLE
Remove System module and add Settings module

### PR DESCRIPTION
**Pull request by Awea**

### CODE REVIEW

**Comment by robottokauf3** [comment]
@Awea Thanks for putting this draft together!  

When you have a chance could you let me know what, if any, additional changes you are planning?  I'm working on some local updates to prep for v0.13 which I hope to wrap up this weekend and I don't want us duplicating any efforts.

**Comment by Awea** [comment]
@robottokauf3 Thanks you for releasing this library!

I'm working on child routes for [Settings](https://docs.meilisearch.com/references/settings.html). If I got the [update distinct attribute](https://docs.meilisearch.com/references/distinct_attribute.html#update-distinct-attribute) route working tomorrow this will be all for that pull-request. 

Next week I was planning to work on the test suite, which fail sometimes because the index is not in the expected state (or something like that).

Other than that, I have created some modules to: 
- handle the index creation/configuration when the application starts 
- deal with `facetsFilters` parameters 

I think about making these modules more generic so they can be reusable and I can make another pull request someday. And this is the end of my todo-list :p 

So, are we duplicating efforts? :)

**Comment by Awea** [comment]
Hi @robottokauf3, hope you're fine. 

I've updated the tests in my last commit, now they won't fail because of an incorrect index state. Let me know, when you have the time, if I need to change something in this PR so it can be merged :)

**Comment by robottokauf3** [comment]
Sounds good. 

Sorry for the delay here, I'm in the process of moving and it's consuming significantly more time than planned. 

That being said, I should be settled by Tuesday and I'm looking forward to taking a closer look at this PR and updating this repo.

**Review by robottokauf3 — APPROVED** [review]
I'll finally be back at the computer on a regular basis.  Thanks for the taking the time to create this PR looks good. Going to merge.

**Pull request merged**
